services:
  - type: pserv
    name: your-app-ollama  # Substitua por um nome significativo para seu serviço
    region: oregon
    runtime: docker
    dockerContext: ./ollama
    dockerfilePath: ./ollama/Dockerfile
    plan: starter
